//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHSCMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTable
    {
        public long DocID { get; set; }
        public Nullable<short> TypeID { get; set; }
        public byte[] Document_Data { get; set; }
        public string Document_Name { get; set; }
        public string Content_Type { get; set; }
        public long ReferenceID { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<long> VendorID { get; set; }
    
        public virtual DocumentTypeTable DocumentTypeTable { get; set; }
    }
}
